#!/bin/bash

# Validate root user.
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root." 1>&2
   exit 1
fi

: "${UKONVRT_APP?Please set env variable UKONVRT_APP to full path of application to convert to unikernel.}"
: "${UKONVRT_OUT?Please set env variable UKONVRT_OUT to host local directory where application unikernel image will be saved.}"

# TODO: Check for KVM and Docker.
echo "This tool depends on KVM and Docker."

# Determine target architecture for the application.
# Default to x86-64.
ARCH="x86-64"
APP_TARGET_ARCH=`file $UKONVRT_APP | awk -F[:,] '{print $3}' | tr -d '[:space:]'`
if [ "$APP_TARGET_ARCH" == "x86-64" ] || [ "$APP_TARGET_ARCH" == "ARMaarch64" ]; then
    ARCH=$APP_TARGET_ARCH
fi

# Launch a privileged container with host networking to build application unikernel.
# Privileged: required for container to spawn intermediate OSv qemu VM on the host during build.
# Host networking: required for Capstan to check for remote images:
# https://github.com/cloudius-systems/capstan/blob/1d300adeefd9750c4a0821847e57b1617bb70bfb/util/s3_repository.go#L179
/usr/bin/docker run --net=host -v ${UKONVRT_APP}:${UKONVRT_APP} -v ${UKONVRT_OUT}:/root/.capstan/repository --privileged -e APP=${UKONVRT_APP} -e UKONVRT_JAVA_MAIN=${UKONVRT_JAVA_MAIN} myechuri/ukonvrt:${ARCH}
