#!/bin/bash

: "${UKONVRT_APP?Please set env variable UKONVRT_APP to full path of application to convert to unikernel.}"
: "${UKONVRT_OUT?Please set env variable UKONVRT_OUT to host local directory where application unikernel image will be saved.}"

/usr/bin/docker run -it --net=host -v ${UKONVRT_APP}:${UKONVRT_APP} -v ${UKONVRT_OUT}:/root/.capstan/repository --privileged -e APP=${UKONVRT_APP} myechuri/ukonvrt
